src/Entity/Location.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use OpenApi\Annotations as OA;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LocationRepository")
 * @OA\Schema()
 */
class Location
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @OA\Property(type="string")
     * @Assert\NotBlank
     */
    private $City;

    /**
     * @ORM\Column(type="string", length=255)
     * @OA\Property(type="string")
     * @Assert\NotBlank
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255)
     * @OA\Property(type="string")
     * @Assert\NotBlank
     */
    private $address;

    /**
     * @ORM\Column(type="integer")
     * @OA\Property(type="integer")
     * @Assert\NotBlank
     * * @Assert\Length(
     *      min = 5,
     *      max = 5
     * )
     */
    private $zipcode;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Hotel", inversedBy="locations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $hotelId;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): self
    {
        $this->City = $City;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?int
    {
        return $this->zipcode;
    }

    public function setZipcode(int $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getHotelId(): ?Hotel
    {
        return $this->HotelId;
    }

    public function setHotelId(?Hotel $HotelId): self
    {
        $this->HotelId = $HotelId;

        return $this;
    }
}

templates/Hotels.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Hotel!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>ALL The Hotels! ✅</h1>
    {% for hotel in hotels %}
    your files is {{hotel.name}} </a>
    <h2><a href={{ path('Hotelform',{'id': hotel.id})}}> your Hotel is {{hotel.name}}</h2></a><span>with the category: {{hotel.category}}</span>
    <p><img src="{{hotel.image}}"></p>
    <h2>Rating</h2>{% for location in hotel.locations %}
    <h3>{{location.city}} || {{location.state}} || {{location.country}} || {{location.zipcode}} </h3>{% endfor %}
    <p>      
</p>
<p><a href={{path('Hotelform')}}>you can add new Hotel here</a></p>
{% endfor %}
{% endblock %}

templates/Hotelshow.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Hotel!{% endblock %}
{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello Hotel! ✅</h1>
    {% for hotel in hotels %}
    <h2>your Hotel is {{hotel.name}}</h2><span>with the category: {{hotel.category}}</span>
    <p><img src="{{hotel.image}}"></p>
    <h2>Rating</h2>{% for location in hotel.locations %}
    <h3>{{location.city}} || {{location.state}} || {{location.country}} || {{location.zipcode}} </h3>{% endfor %}
    <p>
        <form action="">
  <p>Rate the Hotel :</p>
  <div>
    <input type="radio" id="contactChoice1"
     name="contact" value="0">
    <label for="contactChoice1">0</label>

    <input type="radio" id="contactChoice1"
     name="contact" value="1">
    <label for="contactChoice1">1</label>

    <input type="radio" id="contactChoice1"
     name="contact" value="2">
    <label for="contactChoice1">2</label>

    <input type="radio" id="contactChoice1"
     name="contact" value="3">
    <label for="contactChoice1">3</label>

    <input type="radio" id="contactChoice1"
     name="contact" value="04>
    <label for="contactChoice1">4</label>

    <input type="radio" id="contactChoice1"
     name="contact" value="5">
    <label for="contactChoice1">5</label>
  </div>
  <div>
    <button type="submit">Envoyer</button>
  </div>
</form>
</p>
<p><a href={{path('Hotelform')}}>you can add new Hotel here</a></p>
<p><a href={{path('Hotelform',{'id': hotel.id})}}>Modify your hotel here</a></p>
{% endfor %}
{% endblock %}

templates/NewHotel.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello Hoteler!{% endblock %}
{% block body %}
{% if editmode %}
<h1>Add new Hotel<h1/>
{% else %}
<h1>modify Hotel<h1/>
{% endif %}
{{ form_start(formhotel) }}
{{ form_row(formhotel.name) }}
{{ form_row(formhotel.image) }}
<label for="pet-select">Choose a your category:</label>
<select name="category" id="hotel-select">
    <option value="">--Please choose the category--</option>
    <option value="hotel">hotel</option>
    <option value=" alternative"> alternative</option>
    <option value="hostel">hostel</option>
    <option value="lodge">lodge</option>
    <option value="resort">resort</option>
    <option value="guest-house">guest-house</option>
</select>
{{ form_row(formhotel.price) }}
{{ form_start(formlocation) }}
{{ form_widget(formlocation) }}
{{form_end(formlocation)}}
{{form_end(formhotel)}}
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>